echo REACH_CONNECTOR_MODE: 
echo $REACH_CONNECTOR_MODE

echo REACH_DEBUG: 
echo $REACH_DEBUG

echo ALGO_SERVER: 
echo $ALGO_SERVER

echo ALGO_TOKEN:
echo $ALGO_TOKEN

echo ALGO_PORT:
echo $ALGO_PORT

echo ALGO_INDEXER_SERVER:
echo $ALGO_INDEXER_SERVER

echo ALGO_INDEXER_TOKEN:
echo $ALGO_INDEXER_TOKEN

echo ALGO_INDEXER_PORT:
echo $ALGO_INDEXER_PORT

echo REACH_RPC_SERVER: 
echo $REACH_RPC_SERVER

echo ALGO_FAUCET_PASSPHRASE:
echo $ALGO_FAUCET_PASSPHRASE

echo REACH_RPC_PORT: 
echo $REACH_RPC_PORT

echo REACH_RPC_TLS_REJECT_UNVERIFIED:
echo $REACH_RPC_TLS_REJECT_UNVERIFIED

echo REACH_RPC_KEY: 
echo $REACH_RPC_KEY

echo REACH_RPC_TIMEOUT:
echo $REACH_RPC_TIMEOUT

echo NODE_TLS_REJECT_UNAUTHORIZED:
echo $NODE_TLS_REJECT_UNAUTHORIZED

echo REACH_VERSION:
echo $REACH_VERSION

echo REACH_RPC_TLS_CRT:
echo $REACH_RPC_TLS_CRT

echo REACH_RPC_TLS_PASSPHRASE:
echo $REACH_RPC_TLS_PASSPHRASE

echo ETH_NODE_URI:
echo $ETH_NODE_URI

echo ETH_NODE_NETWORK:
echo $ETH_NODE_NETWORK